from typing import Any, Protocol


class WorkflowBackend(Protocol):
    async def start(self, workflow_type: str, workflow_id: str, payload: dict[str, Any]) -> str: ...

    async def status(self, workflow_id: str) -> str: ...

    async def cancel(self, workflow_id: str) -> None: ...

    async def resume(self, workflow_id: str) -> None: ...

